databases:
  - name: yuyuweb-db
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: yuyuweb
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn yuyuweb.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yuyuweb-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION # 这里的 python version 是用来指定 Python 版本的，比如这里我用的是 3.11.4。
        value: 3.9.6